on: push

name: Commit Message

# NOTE: Skip check on PR so as not to confuse contributors
# NOTE: Also install a PR title checker so we don't mess up merges
jobs:
  commit-msg:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Conventional Commitlint
        uses: opensource-nepal/commitlint@v1
