name: Release

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v5

    - uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.10"

    - name: Build
      run: uv run --group release python setup.py sdist bdist_wheel

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
