on: ["push", "pull_request"]

name: Test

concurrency:
  # Cancel older, in-progress jobs from the same PR, same workflow.
  # use run_id if the job is triggered by a push to ensure
  # push-triggered jobs to not get canceled.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v5

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
              python-version: "3.10"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install . --group lint

        - name: Run Ruff Lint
          run: ruff check .

        - name: Run Ruff Format
          run: ruff format --check .

        - name: Run mdformat
          run: mdformat . --check

    type-check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - uses: astral-sh/setup-uv@v6
          with:
            # NOTE: Use minimum supported Python version to avoid using new syntax
            python-version: "3.10"

        - name: Run MyPy
          run: uv run --group lint --group test mypy .

    functional:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
        - uses: actions/checkout@v5
          with:
            fetch-depth: 0

        - uses: astral-sh/setup-uv@v6
          with:
            python-version: ${{ matrix.python-version }}

        - name: Run Tests
          run: uv run --group test pytest -m "not fuzzing" -s

#    fuzzing:
#        runs-on: ubuntu-latest
#
#        strategy:
#            fail-fast: true
#
#        steps:
#        - uses: actions/checkout@v5
#
#        - uses: astral-sh/setup-uv@v6
#          with:
#            python-version: "3.10"
#
#        - name: Run Tests
#          run: uv run --group test pytest -m "fuzzing" --no-cov -s
